variables:
    {itemList::*} = none
    {chestLocations::%player%} = none
    {expPoints::%player%} = 0

#운영자 전용 아이템 인벤토리(명령어로 등록한 아이템들이 저장됨) 아이템 들고 명령어 입력
command /아이템추가:
    trigger:
        if player's tool is set:
            add player's tool to {itemList::*}
            send "&a아이템이 리스트에 추가되었습니다." to player
        else:
            send "&c들고 있는 아이템이 없습니다." to player

command /아이템지급:
    permission: op
    trigger:
        # 임시 상자 생성 (6줄짜리, 총 54칸)
        set {_inventory} to a new chest inventory with 6 rows named "운영자의 창고"
        
        # 상자에 아이템 추가
        
        add book named "&d&l[&fTitle&d&l]&f" with lore "&fRight-click to obtain this title." to {_inventory}
        add book named "&d&l[&fTitle&d&l]&f &d&l[운영자]" with lore "&fRight-click to obtain this title." to {_inventory}

        add stick named "&d&l[운영자의 죽음의 빠따]&r" with lore "운영자 전용 빠따" to {_inventory}
        loop all items in {_inventory}:
            if name of loop-item contains "§" and "운영자의":
                enchant loop-item with unbreaking 10
                enchant loop-item with mending
                enchant loop-item with sharpness 100
                enchant loop-item with protection 100
                enchant loop-item with breach 4
        add stick named "&d&l[운영자의 죽음의 밀치기 빠따]&r" with lore "운영자 전용 빠따" to {_inventory}
        loop all items in {_inventory}:
            if name of loop-item contains "§" and "운영자의 죽음의 밀치기":
                enchant loop-item with unbreaking 10
                enchant loop-item with mending
                enchant loop-item with knockback 10
                enchant loop-item with protection 100
	add flower banner pattern named "&e시작의 압긍마을 귀환서&r" with lore "시작의 압긍마을로 귀환시켜주는 스크롤" to {_inventory}

        loop {itemList::*}:
            add loop-value to {_inventory}
        # 플레이어에게 상자 보여주기
        open {_inventory} to player

